apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: k17e3d39j-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/k17e3d39j-java-quarkus-gitops